#!/usr/bin/env bash

# An entry which will initialize the scripts required to load a workflow

set -e

function usage {
  echo "usage: $0 <target_workflow> <args>"
}

if [ -z "${1}" ]; then
  printf '%s\n' "Target workflow is missing." >&2
  usage
  exit 1;
fi

if [ $CI == 'true' ]; then
  test -f $LOAD_ENV && source $LOAD_ENV
fi

WORKFLOW_SCRIPT=$1

shift 1

$WORKFLOW_SCRIPT $@
