#!/usr/bin/env bash

# A runner which will initialize the scripts required to load a workflow or test

set -e

function usage {
  echo "usage: $0 <target_workflow> <args>"
}

if [ -z "${1}" ]; then
  printf '%s\n' "Target workflow is missing." >&2
  usage
  exit 1;
fi

ORIGINAL_PWD="$PWD"

if [ "$CI" == 'true' ]; then
  TESTS_DIR="/tmp/tests"
else
  TESTS_DIR="$PWD/tests"
fi

if [ $1 == 'test' ]; then
  if [ "$CI" == 'true' ]; then
    test -f $LOAD_ENV && source $LOAD_ENV
  fi
  for dir in `ls $TESTS_DIR`; do
    TEST_DIR=$TESTS_DIR/$dir
    if [ -d $TEST_DIR ]; then
      cd $TEST_DIR/assets
      ../run.sh
      cd $ORIGINAL_PWD
    fi
  done
else
  WORKFLOW_SCRIPT=$1
  shift 2
  $WORKFLOW_SCRIPT "$@"
fi
